# Panel or 3 dimentional

1. Items - axis 0, each item corresponds to a DataFrame contained inside
2. major_axis - axis 1, it is the index(rows) of each of the DataFrames
3. minor_axis - axis 2, it is the columns of each of the DataFrames

Syntex: pandas.Panel(data, items, major_axis, minor_axis, dtype,copy)

*Input should be only arrays

In [2]:
import numpy
MyData=numpy.random.randn(2,3,4)
print(MyData)

import pandas
panal_Data=pandas.Panel(data=MyData)
print(panal_Data)

[[[ 1.21183373  0.25788685 -0.01431211  1.1614881 ]
  [ 0.15727292 -0.33372606  0.85056527 -1.15091328]
  [-1.19025862 -0.27230085 -0.43798607 -1.05300543]]

 [[-0.69833884 -0.40275203 -0.27806039  0.43522735]
  [ 0.80989309  0.70818884  0.21368594  0.94247304]
  [-1.96499562  2.18752723  0.30767358 -1.20440309]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 2
Minor_axis axis: 0 to 3


In [4]:
import numpy
MyData=numpy.random.randn(2,3,4)
print(MyData)

import pandas
panal_Data=pandas.Panel(data=MyData,items=["A","B"],major_axis=["R1","R2","R3"],minor_axis=["C1","C2","C3","C4"])
print(panal_Data)

[[[ 0.66002167  0.92968441  0.50070859 -0.06664003]
  [-1.16614794  1.93984695 -1.03964646  0.00874515]
  [-0.31963883  0.15070578 -0.83331802 -0.09618012]]

 [[-0.6346968  -0.25321277  0.27932563  0.31048973]
  [-0.70235799 -1.47323581 -1.089133    0.09465486]
  [ 1.49162181 -1.86556384  0.77397912 -0.00321102]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: A to B
Major_axis axis: R1 to R3
Minor_axis axis: C1 to C4


# Exercise

In [14]:
import numpy

MyData=[[[1,2,3,4],[4,5,6,8],[8,9,0,1]],[[1,2,3,4],[4,5,6,8],[8,9,0,1]],[[1,2,3,4],[4,5,6,8],[8,9,0,1]]]

print(MyData)

import pandas

panel_Data=pandas.Panel(data=MyData,items=["A","B","C"],major_axis=["1","2","3"],minor_axis=["1","2","3","4"])
print(panel_Data)

[[[1, 2, 3, 4], [4, 5, 6, 8], [8, 9, 0, 1]], [[1, 2, 3, 4], [4, 5, 6, 8], [8, 9, 0, 1]], [[1, 2, 3, 4], [4, 5, 6, 8], [8, 9, 0, 1]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: A to C
Major_axis axis: 1 to 3
Minor_axis axis: 1 to 4


In [17]:
import numpy as np

MyData=np.random.randn(5,8,10)

print(MyData)

import pandas

panel_Data=pandas.Panel(data=MyData)
print(panel_Data)

[[[-3.88424130e-01  2.78610870e-01 -2.93737448e-01  7.75201109e-01
    1.64990497e+00 -1.28811675e+00  6.09276283e-01 -5.71645818e-02
   -6.55527659e-01 -5.70548428e-01]
  [-2.40605415e-01 -2.36970514e-01  1.00550007e+00  5.66709199e-01
    1.38329434e+00  5.36527853e-01  4.20743704e-01  4.32328661e-01
   -1.39565595e-01 -4.74014113e-01]
  [-7.56916720e-01  4.84974938e-01 -9.13978747e-01  1.82357244e+00
    1.57606893e-01  2.71226064e-01 -8.69609027e-01  9.14567189e-01
    1.75707792e-01  1.33363006e+00]
  [-3.73716066e-01  2.95084263e-01  5.21166237e-02  6.85845648e-01
   -2.85233650e-01  7.55954077e-01  6.30983424e-03  9.67352370e-02
   -1.00075460e+00 -1.09113151e-01]
  [-1.59822841e+00 -1.00249907e+00  1.28463900e+00  4.40374647e-01
   -4.58190065e-01 -6.53156104e-01  5.63709843e-01  1.40320433e+00
   -2.34588601e-01 -1.95342869e-01]
  [-9.54941587e-02 -3.14331815e-04  4.69520230e-01  6.13880611e-01
    8.92583031e-01 -2.67053223e-01 -4.66285802e-01  5.15164441e-02
    1.56578479e+