# 2D or 2 Dimentional or DataFrame

Input like:
--------------
1. List
2. Tuple-Not supported
3. Dictionary
4. array
5. Series

Syntanx:
pandas.DataFrame(data,index,columns,dtype,copy)

# List

In [2]:
MyList=[10,"Data",99.5]
print(MyList)

import pandas

dataFrame=pandas.DataFrame(MyList)
print(dataFrame)

[10, 'Data', 99.5]
      0
0    10
1  Data
2  99.5


In [4]:
MyList=[[10,"Data",99.5],[20,"Science",45.6]]
print(MyList)

import pandas

dataFrame=pandas.DataFrame(MyList)
print(dataFrame)

[[10, 'Data', 99.5], [20, 'Science', 45.6]]
    0        1     2
0  10     Data  99.5
1  20  Science  45.6


In [5]:
MyList=[[10,"Data",99.5],[20,"Science",45.6]]
print(MyList)

import pandas

dataFrame=pandas.DataFrame(MyList,index=["R1","R2"],columns=["C1","C2","C3"])
print(dataFrame)

[[10, 'Data', 99.5], [20, 'Science', 45.6]]
    C1       C2    C3
R1  10     Data  99.5
R2  20  Science  45.6


# Tuple

In [7]:
#this program should throw error since Tuple will not work in pandas data frame
MyTuple=((10,"Data",99.5),(20,"Science",45.6))
print(MyTuple)

import pandas

dataFrame=pandas.DataFrame(data=MyTuple,index=["R1","R2"],columns=["C1","C2","C3"])
print(dataFrame)

((10, 'Data', 99.5), (20, 'Science', 45.6))


TypeError: Argument 'rows' has incorrect type (expected list, got tuple)

In [8]:
#one dimentional tuple can be convert to series and than called in dataframe

MyTuple=(10,"Data",99.5)
print(MyTuple)

import pandas

series_Data=pandas.Series(data=MyTuple)

print(series_Data)

dataFrame=pandas.DataFrame(data=series_Data)
print(dataFrame)

(10, 'Data', 99.5)
0      10
1    Data
2    99.5
dtype: object
      0
0    10
1  Data
2  99.5


In [9]:
#one dimentional tuple can be convert to series and than called in dataframe

MyTuple=(10,"Data",99.5)
print(MyTuple)

import pandas

series_Data=pandas.Series(data=MyTuple)

print(series_Data)

dataFrame=pandas.DataFrame(data=series_Data,index=["R1","R2","R3"])
print(dataFrame)

(10, 'Data', 99.5)
0      10
1    Data
2    99.5
dtype: object
      0
R1  NaN
R2  NaN
R3  NaN


# Dictionary

In [10]:
MyDict={"Name":"Apple","shape":"circle"}
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict)
print(dataFrame)

{'Name': 'Apple', 'shape': 'circle'}


ValueError: If using all scalar values, you must pass an index

In [11]:
MyDict={"Name":["Apple","Orange"],"shape":["circle","circle"]} #value should be list or tupe so that it will generate index, otherwise it will throw error
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict)
print(dataFrame)

{'Name': ['Apple', 'Orange'], 'shape': ['circle', 'circle']}
     Name   shape
0   Apple  circle
1  Orange  circle


In [13]:
MyDict={"Name":["Apple","Orange"],"shape":["circle","circle"],"price":[10,23]} 
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict,index=["R1","R2"])
print(dataFrame)

{'Name': ['Apple', 'Orange'], 'shape': ['circle', 'circle'], 'price': [10, 23]}
      Name   shape  price
R1   Apple  circle     10
R2  Orange  circle     23


In [14]:
MyDict={"Name":["Apple","Orange"],"shape":["circle","circle"],"price":[10,23]} 
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict,index=["R1","R2"],columns=["price","Name","shape"])
print(dataFrame)

{'Name': ['Apple', 'Orange'], 'shape': ['circle', 'circle'], 'price': [10, 23]}
    price    Name   shape
R1     10   Apple  circle
R2     23  Orange  circle


In [15]:
MyDict={"Name":["Apple","Orange"],"shape":["circle","circle"],"price":[10,23]} 
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict,index=["R1","R2"],columns=[1,2,3])
print(dataFrame)

{'Name': ['Apple', 'Orange'], 'shape': ['circle', 'circle'], 'price': [10, 23]}
      1    2    3
R1  NaN  NaN  NaN
R2  NaN  NaN  NaN


# Array

In [18]:
import numpy
MyData=numpy.array([[10,20,30],[40,50,60]])

print(MyData)
print(type(MyData))

import pandas

dataFrame=pandas.DataFrame(data=MyData)
print(dataFrame)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
    0   1   2
0  10  20  30
1  40  50  60


In [21]:
import numpy
MyData=numpy.array([[10,20,30],[40,50,60]])

print(MyData)
print(type(MyData))
print()

import pandas

dataFrame=pandas.DataFrame(data=MyData,index=["R1","R2"],columns=["C1","C2","C3"])
print(dataFrame)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>

    C1  C2  C3
R1  10  20  30
R2  40  50  60


#Exercise:
---------------

In [29]:
#dataframe for 2 dimentional tuple:

myTuple=((1,2,3),(4,5,6))
print(myTuple)

myList=list(myTuple) 

print(myList)

import pandas

dataFrame=pandas.DataFrame(data=myList,index=["R1","R2"],columns=["C1","C2","C3"])
print(dataFrame)


((1, 2, 3), (4, 5, 6))
[(1, 2, 3), (4, 5, 6)]
    C1  C2  C3
R1   1   2   3
R2   4   5   6


In [40]:
MyDict={"FName":["Jeeva","Balan","Karthik","Poovaraso"],"LName":["Madhu","Siva"],"Age":[29,23,24,22]} 
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict,index=[1,2,3,4],columns=["FName","Age"])
print(dataFrame)

{'FName': ['Jeeva', 'Balan', 'Karthik', 'Poovaraso'], 'LName': ['Madhu', 'Siva'], 'Age': [29, 23, 24, 22]}
       FName  Age
1      Jeeva   29
2      Balan   23
3    Karthik   24
4  Poovaraso   22


In [45]:
MyDict={"FName":["Jeeva","Balan","Karthik","Poovaraso"],"LName":["Madhu","Siva","",""],"Age":[29,23,24,22]} 
print(MyDict)

import pandas

dataFrame=pandas.DataFrame(data=MyDict,index=[1,2,3,4],columns=["FName","LName","Age"])
print(dataFrame)

{'FName': ['Jeeva', 'Balan', 'Karthik', 'Poovaraso'], 'LName': ['Madhu', 'Siva', '', ''], 'Age': [29, 23, 24, 22]}
       FName  LName  Age
1      Jeeva  Madhu   29
2      Balan   Siva   23
3    Karthik          24
4  Poovaraso          22


In [48]:
MyList=[[10,"Data",99.5],[20,"Science"],[]]
print(MyList)

import pandas

dataFrame=pandas.DataFrame(MyList)
print(dataFrame)

[[10, 'Data', 99.5], [20, 'Science'], []]
      0        1     2
0  10.0     Data  99.5
1  20.0  Science   NaN
2   NaN     None   NaN


In [55]:
MyList=[[10,23,99.5],["j",5],[]]
print(MyList)

import pandas

dataFrame=pandas.DataFrame(MyList)
print(dataFrame)

[[10, 23, 99.5], ['j', 5], []]
      0     1     2
0    10  23.0  99.5
1     j   5.0   NaN
2  None   NaN   NaN
