
1. Select the data from the panel using
  1. items
  2. Major_axis
  3. Minor_axis
   
 

In [4]:
#printing single item
import numpy
MyData=numpy.random.randn(2,3,4)
print(MyData)

import pandas
panal_Data=pandas.Panel(data=MyData,items=["A","B"],major_axis=["R1","R2","R3"],minor_axis=["C1","C2","C3","C4"])
print(panal_Data)
print(panal_Data["A"]) #printing single item

[[[ 1.22873629  0.30851502  1.85853769 -1.655059  ]
  [ 0.10016562  1.37679601  0.56614398 -1.4580943 ]
  [ 0.80342793 -0.54105575 -1.3919495   1.12372948]]

 [[-1.48608603 -0.3195224  -0.50161891  1.25355059]
  [ 1.28016606  2.13248647 -2.24031603  1.68081343]
  [ 0.45903777  0.4883715  -0.03110636 -0.28449813]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: A to B
Major_axis axis: R1 to R3
Minor_axis axis: C1 to C4
          C1        C2        C3        C4
R1  1.228736  0.308515  1.858538 -1.655059
R2  0.100166  1.376796  0.566144 -1.458094
R3  0.803428 -0.541056 -1.391950  1.123729


In [5]:
#printing major axis
import numpy
MyData=numpy.random.randn(2,3,4)
print(MyData)

import pandas
panal_Data=pandas.Panel(data=MyData,items=["A","B"],major_axis=["R1","R2","R3"],minor_axis=["C1","C2","C3","C4"])
print(panal_Data)
print(panal_Data.major_xs("R1")) #printing major axis

[[[ 0.01076208 -0.01684369  0.79870043 -1.92717828]
  [ 0.21465731  1.5912075  -0.35476676  0.05940478]
  [-0.16191328  0.72417493  0.86718629 -1.8563862 ]]

 [[ 0.53862013 -0.40890649  1.20681821  0.54279205]
  [-0.93050667 -0.82996596  0.89479227  2.16163188]
  [-1.32929741  1.14648166  0.75555409 -1.23539954]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: A to B
Major_axis axis: R1 to R3
Minor_axis axis: C1 to C4
           A         B
C1  0.010762  0.538620
C2 -0.016844 -0.408906
C3  0.798700  1.206818
C4 -1.927178  0.542792


C:\Users\HP1\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3296: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [7]:
#printing minor axis
import numpy
MyData=numpy.random.randn(2,3,4)
print(MyData)

import pandas
panal_Data=pandas.Panel(data=MyData,items=["A","B"],major_axis=["R1","R2","R3"],minor_axis=["C1","C2","C3","C4"])
print(panal_Data)
print(panal_Data.minor_xs("C2")) #printing minor axis

[[[ 1.34401544e+00 -1.18257452e+00 -1.06823633e+00 -3.91919234e-01]
  [-7.54578375e-01  1.22634697e+00  4.98464215e-01 -1.35217806e+00]
  [ 1.46015328e+00 -8.66335929e-01 -5.64201901e-02  1.50683219e+00]]

 [[-1.66490295e+00  2.57503538e-03 -3.07402434e+00 -8.55701113e-01]
  [-1.46394778e+00 -1.05055178e+00 -1.33854141e+00 -1.27565934e+00]
  [ 3.17107208e-01 -8.40885413e-01  6.34260094e-01  1.93454050e-01]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: A to B
Major_axis axis: R1 to R3
Minor_axis axis: C1 to C4
           A         B
R1 -1.182575  0.002575
R2  1.226347 -1.050552
R3 -0.866336 -0.840885
